# Functions to interact with the GitHub API

# github_tools.py
import os
from github import Github
from langchain_core.tools import tool
from dotenv import load_dotenv
import uuid

load_dotenv()

# Initialize GitHub client
gh_token = os.getenv("GITHUB_TOKEN")
gh_client = Github(gh_token)

@tool
def get_github_file(repo_name: str, file_path: str) -> str:
    """
    Fetches the content of a specific file from a GitHub repository.
    Use this tool to read the code that might be causing the pipeline error.
    """
    try:
        repo = gh_client.get_repo(repo_name)
        file_content = repo.get_contents(file_path)
        return file_content.decoded_content.decode("utf-8")
    except Exception as e:
        return f"Error reading file: {str(e)}"

@tool
def create_pull_request(repo_name: str, file_path: str, new_code: str, commit_message: str) -> str:
    """
    Creates a new branch, updates the broken file with the new code, and opens a Pull Request.
    Call this tool ONLY after you have completely figured out the fix.
    """
    try:
        repo = gh_client.get_repo(repo_name)
        
        # 1. Get the default branch (usually 'main' or 'master')
        default_branch = repo.default_branch
        sb = repo.get_branch(default_branch)
        
        # 2. Create a unique branch name for the AI fix
        new_branch_name = f"patchpilot-fix-{uuid.uuid4().hex[:6]}"
        repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=sb.commit.sha)
        
        # 3. Get the specific file we want to update
        file = repo.get_contents(file_path, ref=default_branch)
        
        # 4. Update the file on the new branch
        repo.update_file(
            file.path,
            commit_message,
            new_code,
            file.sha,
            branch=new_branch_name
        )
        
        # 5. Open the Pull Request
        pr = repo.create_pull(
            title=f"PatchPilot Fix: {commit_message}",
            body="🤖 This PR was automatically generated by PatchPilot to fix a pipeline failure. Please review the code changes carefully.",
            head=new_branch_name,
            base=default_branch
        )
        return f"Success! Pull Request created at: {pr.html_url}"
    
    except Exception as e:
        return f"Error creating Pull Request: {str(e)}"